### ISSUE TITLE
Errors in FTCSCOUT when setting up list dimensions

### ISSUE THREAD

**Issue by adriweb** [hchhaya/FTCScouting#1]
Hi Harshal!

I believe you intended to have code "comments" at the beginning, by starting with a `"` for the several `->dim(` lines, but it turns out the `->` implicitly closes strings, it tries to assign that string to the dimension of the lists, which fails with a Data Type error.

I guess we need a _real_ comment feature in TI-Basic :eyes:

Screenshot, in case I wasn't clear:
![image](https://github.com/hchhaya/FTCScouting/assets/660896/bc3cfefd-84d1-4222-adbb-fdca03d45c1b)

_**Edit**: the same kind of errors happen later on with other commands_

**Comment by hchhaya** [comment]
Thanks for catching this. I had uploaded the wrong file my mistake. Your point about a "real comment feature" is well-taken :)
The updated version doesn't have this problem.
